### ISSUE TITLE
Implement filesystem operations via zookeeper

### ISSUE THREAD

**Issue by pelmers** [Rice-Comp413-2016/RDFS#35]
1. Add methods to zk_nn_client corresponding to handlers that touch the namespace.
2. Call the methods from ClientNameNodeTranslator

in progress in zookkerrplus

**Comment by Drazcmd** [comment]
(Just so I don't forget since I had trouble figuring out which exact files needed to be edited)

This header file lists all the methods we gotta add still:
https://github.com/Rice-Comp413-2016/RDFS/blob/zookkerrplus/rice-namenode/ClientNamenodeProtocolImpl.h

It'll be calling stuff from this file, which also needs some work: 
https://github.com/Rice-Comp413-2016/RDFS/blob/zookkerrplus/zookeeper/source/zk_nn_client.cc

**Comment by pelmers** [comment]
- [x] std::string getFileInfo(std::string);
- [ ] std::string mkdir(std::string);
- [ ] std::string destroy(std::string);
- [x] std::string create(std::string);
- [x] std::string getBlockLocations(std::string);
- [ ] std::string getServerDefaults(std::string);
- [ ] std::string renewLease(std::string);
- [x] std::string complete(std::string);
- [ ] std::string setReplication(std::string);
- [ ] std::string rename(std::string);
- [ ] std::string rename2(std::string);
- [ ] std::string append(std::string);
- [ ] std::string setPermission(std::string);
- [ ] std::string recoverLease(std::string);
- [ ] std::string concat(std::string);
- [ ] std::string abandonBlock(std::string input);
